language: java
jdk:
- openjdk8

script:
- wget https://jitpack.io/com/github/takemikami/rdflint/0.0.1/rdflint-0.0.1-all.jar
- java -jar rdflint-0.0.1-all.jar -baseuri https://sparql.crssnky.xyz/imasrdf/
