name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rdflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - uses: imas/setup-rdflint@v2

    - name: Run rdflint (Clothes_Own)
      run: rdflint -config .rdflint/Clothes_Own.yml

    - name: Run rdflint (Unit_memberOf)
      run: rdflint -config .rdflint/Unit_memberOf.yml

    - name: Run rdflint
      run: |
        echo "::add-matcher::.github/rdflint-annotations.json"
        rdflint -config .rdflint/rdflint-config.yml
        echo "::remove-matcher owner=rdflint::"
