name: sparqlmarkdown
on:
  push:

jobs:
  sparqlmarkdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: setup sparql-markdown
      run: wget https://jitpack.io/com/github/takemikami/sparql-markdown/5b67ba7a27/sparql-markdown-5b67ba7a27-all.jar
    - name: update markdown
      run: find sparql_samples -name "*.md" | xargs java -jar sparql-markdown-5b67ba7a27-all.jar --replace --files
    - name: commit
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        # git branch
        git push origin $GITHUB_REF
